apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
---
kind: Service
apiVersion: v1
metadata:
  name:  nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - nginx.dev.example.com
    - hosts:
        - dev.example.com
      secretName: nginx-tls-home
  rules:
    - host: dev.example.com
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
    - host: nginx.dev.example.com
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80

